# Generated by Django 3.0.3 on 2020-04-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
